# Generated by Django 6.0 on 2026-10-06 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_description_user_username_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, help_text='Unique username. Only letters, numbers, dots, and underscores are allowed.', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Username must contain only letters, numbers, dots, and underscores.', regex='^[a-zA-Z0-9_.]+$')]),
        ),
    ]
