# Generated by Django 6.0 on 2026-10-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Post Like'), ('dislike', 'Post Dislike'), ('comment', 'Post Comment'), ('reply', 'Comment Reply'), ('follow', 'Follow'), ('unfollow', 'Unfollow'), ('follow_back', 'Follow Back'), ('mention', 'User Mention')], max_length=20),
        ),
    ]
