# Generated by Django 6.0 on 2025-12-16 05:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Post image (JPG, JPEG, or PNG only)', upload_to='post_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('description', models.TextField(help_text='Post description or caption', max_length=500)),
                ('likes_count', models.PositiveIntegerField(default=0, help_text='Number of likes this post has received')),
                ('dislikes_count', models.PositiveIntegerField(default=0, help_text='Number of dislikes this post has received')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this post was created')),
                ('user', models.ForeignKey(help_text='The user who created this post', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], help_text='Whether this is a like or dislike', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this interaction was made')),
                ('post', models.ForeignKey(help_text='The post being liked or disliked', on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='posts.post')),
                ('user', models.ForeignKey(help_text='The user who made this interaction', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post Interaction',
                'verbose_name_plural': 'Post Interactions',
                'unique_together': {('user', 'post')},
            },
        ),
    ]
